# Generated by Django 4.2.4 on 2023-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=0, max_length=100, verbose_name='категория'),
            preserve_default=False,
        ),
    ]
